env:
  TERM: alacritty

# Upon opening alacritty attach to last or new tmux session
# shell:
#   program: /bin/zsh
#   args:
#     - -l
#     - -c
#     - "tmux attach || tmux"
# Display tabs using this many cells (changes require restart)
tabspaces: 4

# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors: true

live_config_reload: true

# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: "FiraCode NF"
    # family: "Roboto Mono"
    # family: "Hack"
    # family: "Droid Sans Mono"
    # Style can be specified to pick a specific face.
    style: Retina

  # The bold font face
  bold:
    family: "FiraCode NF"
    # family: "Roboto Mono"
    # family: "Hack"
    # family: "Droid Sans Mono"
    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italic:
    # family: "Roboto Mono"
    # family: "Droid Sans Mono"
    family: "FiraCode NF"
    # Style can be specified to pick a specific face.
    style: Italic

  # Point size of the font
  size: 11.0
  use_thin_strokes: true
# Window opacity as a floating point number from `0.0` to `1.0`.
# The value `0.0` is completely transparent and `1.0` is opaque.
window:
  decorations: full
  # Cursor colors
  #   Colors which should be used to draw the terminal cursor.
  #   Allowed values are CellForeground/CellBackground, which reference the
  #   affected cell, or hexadecimal colors like #ff00ff.
cursor:
  text: '#000000'
  cursor: '#ff00ff'
  style:
    shape: Block
    blinking: Always
  blink_interval: 500
  # Colors (Tender)
colors:
  name: VisiBlue
  author: ""
  primary:
    background: "#000000"
    foreground: "#666699"
  cursor:
    text: "#000000"
    cursor: "#666699"
  normal:
    black: "#333366"
    red: "#6666cc"
    green: "#0099cc"
    yellow: "#3366cc"
    blue: "#006699"
    magenta: "#0066ff"
    cyan: "#669999"
    white: "#99cccc"
  bright:
    black: "#333399"
    red: "#9999ff"
    green: "#00ccff"
    yellow: "#6699ff"
    blue: "#0099cc"
    magenta: "#0099ff"
    cyan: "#66cccc"
    white: "#ccffff"
theme: Visiblue
