env:
  TERM: alacritty

# Display tabs using this many cells (changes require restart)
tabspaces: 4

# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors: true

# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: "FiraCode NF"
    # family: "Roboto Mono"
    # family: "Hack"
    # family: "Droid Sans Mono"
    # Style can be specified to pick a specific face.
    style: Retina

  # The bold font face
  bold:
    family: "FiraCode NF"
    # family: "Roboto Mono"
    # family: "Hack"
    # family: "Droid Sans Mono"
    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italic:
    # family: "Roboto Mono"
    # family: "Droid Sans Mono"
    family: "FiraCode NF"
    # Style can be specified to pick a specific face.
    style: Italic

  # Point size of the font
  size: 11.0
